defmodule Pelemay.Generator.Interface do
  alias Pelemay.Generator
  alias Pelemay.Db
  alias Pelemay.Generator

  require Logger

  def generate(module) when is_atom(module) do
    case generate_functions(module) do
      "" ->
        {:error, "Don't need defpelemay"}

      funcs ->
        str = """
        # This file was generated by Pelemay.Generator.Interface
        defmodule #{Generator.nif_module(module)} do
          @compile {:autoload, false}
          @on_load :init

          require Logger

          def init do
            init_cpu_info()
            load_nifs()
            :ok
          end

          def load_nifs do
            nif_file = "\#{Pelemay.Generator.libnif(#{module})}"
            Logger.debug("[Pelemay] library.exists? = \#{Path.wildcard(\"\#{nif_file}\.{dll,so}\") |> File.exists?()}")
            case :erlang.load_nif(nif_file, 0) do
              :ok ->
                Logger.debug("[Pelemay] load_nif success")
                :ok
              other -> Logger.debug(#{~S/"[Pelemay] Failed to load NIF:#{other}"/})
            end
          end

          def init_cpu_info do
            :ets.new(:cpu_info, [:set, :public, :named_table])
            :ets.insert(:cpu_info, {:runtime_info, CpuInfo.all_profile()})
            Logger.debug("[Pelemay] init_cpu_info success")
          end

        #{funcs}
        end
        """

        Generator.stub(module) |> File.write(str)
        Generator.stub(module) |> Code.compile_file(Generator.ebin())

        Code.append_path(Generator.ebin())
        :ok
    end
  end

  defp generate_functions(module) do
    Db.get_functions()
    |> Enum.map(&generate_function(module, &1))
    |> List.to_string()
  end

  defp generate_function(module, [func_info]) do
    generate_function(module, func_info)
  end

  defp generate_function(module, %{impl: true} = func_info) do
    %{
      nif_name: nif_name,
      module: _,
      function: _,
      arg_num: num
    } = func_info

    args = generate_string_arguments(num)
    args_active = generate_string_arguments_active(num)
    args_inspect = generate_string_arguments_inspect(num)

    """
      def #{nif_name}(#{args_active}) do
        try do
          #{nif_name}_nif(#{args_active})
        catch
          :error, :badarg ->
            runtime_info = try do
              :ets.lookup(:cpu_info, :runtime_info)
            catch
              :error, :badarg ->
                init_cpu_info()
                :ets.lookup(:cpu_info, :runtime_info)
            end
            if Pelemay.Db.get_flag(:put_error_log) do
              Logger.error("[Pelemay] badarg on #{Generator.nif_module(module)}.#{nif_name}")
              Logger.error("[Pelemay] args: #{args_inspect}")
            end
            try do
              if Pelemay.Db.get_flag(:put_error_log) do
                Logger.error("[Pelemay] compile_time_info = \#{Pelemay.eval_compile_time_info() |> elem(1) |> Keyword.get(:compile_time_info) |> inspect}")
              end
            rescue
              _e in Code.LoadError -> 
                if Pelemay.Db.get_flag(:put_error_log) do
                  Logger.error("[Pelemay] compile_time_info = nil")
                end
            end
            if Pelemay.Db.get_flag(:put_error_log) do
              Logger.error("[Pelemay] runtime_info = #\{runtime_info |> inspect}")
            end
            :erlang.error(:badarg)
        end
      end

      def #{nif_name}_nif(#{args}), do: raise "NIF #{nif_name}/#{num} not implemented"

    """
  end

  defp generate_function(_module, %{impl: false}) do
    ""
  end

  defp generate_function(_module, []), do: []

  defp generate_string_arguments(num) do
    1..num
    |> Enum.reduce(
      "",
      fn
        x, "" -> "_arg#{x}"
        x, acc -> acc <> ", _arg#{x}"
      end
    )
  end

  defp generate_string_arguments_active(num) do
    1..num
    |> Enum.reduce(
      "",
      fn
        x, "" -> "arg#{x}"
        x, acc -> acc <> ", arg#{x}"
      end
    )
  end

  def generate_string_arguments_inspect(num) do
    1..num
    |> Enum.reduce(
      "",
      fn
        x, "" -> "arg#{x} = \#{arg#{x} |> inspect}"
        x, acc -> acc <> ", arg#{x} = \#{arg#{x} |> inspect}"
      end
    )
  end
end
