defmodule Pelemay.Generator.Interface do
  alias Pelemay.Generator
  alias Pelemay.Db
  alias Pelemay.Generator

  require Logger

  def generate(module) when is_atom(module) do
    case generate_functions() do
      "" ->
        {:error, "Don't need defpelemay"}

      funcs ->
        str = """
        # This file was generated by Pelemay.Generator.Interface
        defmodule #{Generator.nif_module(module)} do
          @compile {:autoload, false}
          @on_load :load_nifs

          require Logger

          def load_nifs do
            nif_file = "#{Pelemay.Generator.libnif(module)}"
            case :erlang.load_nif(nif_file, 0) do
              :ok -> :ok
              other -> Logger.debug(#{~S/"Failed to load NIF:#{other}"/})
            end
          end

        #{funcs}
        end
        """

        Generator.stub(module) |> File.write(str)

        Generator.stub(module) |> Code.compile_file(Generator.ebin())

        Code.append_path(Generator.ebin())
        :ok
    end
  end

  defp generate_functions do
    Db.get_arguments()
    |> Enum.map(&(&1 |> hd |> generate_function))
    |> List.to_string()
  end

  defp generate_function(name) do   
    """
      def #{name}(_arg1), do: raise "NIF #{name}/1 not implemented"
    """
  end

  #defp generate_function([]), do: []
  
  #defp generate_string_arguments(num) do
   # 1..num
    #|> Enum.reduce(
    #  "",
    #  fn
    #    x, "" -> "_arg#{x}"
    #    x, acc -> acc <> ", _arg#{x}"
    #  end
    #)
  #end
end
