defmodule Pelemay.Generator.Makefile do
  def generate(module) do
    prefix_str = """
    # This file was generated by Pelemay.Generator.Makefile
    TARGET_LIBS := \
    """
 
    str = " $(PREFIX)/libnif#{String.downcase(module |> Atom.to_string() |> String.replace(".", ""))}.so"

    file = Application.app_dir(:pelemay, "priv/generated.mk")

    unless File.exists?(file) do
      file |> File.write(prefix_str)
    end

    file |> File.write(str, [:append])
  end
end
