defmodule Pelemay.Generator.Makefile do
  def generate(_module) do
    prefix_str = """
    # This file was generated by Pelemay.Generator.Makefile
    TARGET_LIBS :=
    """

    file = Application.app_dir(:pelemay, "priv/generated.mk")

    unless File.exists?(file) do
      file |> File.write(prefix_str)
    end
  end
end
